-- Migration: activity feed table, keyset pagination helpers, and write triggers

CREATE TABLE IF NOT EXISTS public.activity_feed (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  seen boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT activity_feed_type_check CHECK (
    type IN ('expense_created', 'expense_deleted', 'settlement_created')
  )
);

CREATE INDEX IF NOT EXISTS idx_activity_feed_user_created_desc
  ON public.activity_feed (user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_activity_feed_user_seen_created_desc
  ON public.activity_feed (user_id, seen, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_activity_feed_user_unseen_desc
  ON public.activity_feed (user_id, created_at DESC, id DESC)
  WHERE seen = false;

ALTER TABLE public.activity_feed ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activity_feed_select_own" ON public.activity_feed;
DROP POLICY IF EXISTS "activity_feed_update_own" ON public.activity_feed;

CREATE POLICY "activity_feed_select_own"
  ON public.activity_feed
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "activity_feed_update_own"
  ON public.activity_feed
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.get_activity_feed_page(
  p_user_id uuid,
  p_limit integer DEFAULT 20,
  p_cursor_created_at timestamptz DEFAULT NULL,
  p_cursor_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  type text,
  metadata jsonb,
  seen boolean,
  created_at timestamptz
)
LANGUAGE sql
STABLE
AS $$
  SELECT af.id, af.type, af.metadata, af.seen, af.created_at
  FROM public.activity_feed af
  WHERE af.user_id = p_user_id
    AND (
      p_cursor_created_at IS NULL
      OR p_cursor_id IS NULL
      OR (af.created_at, af.id) < (p_cursor_created_at, p_cursor_id)
    )
  ORDER BY af.created_at DESC, af.id DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100) + 1;
$$;

GRANT EXECUTE ON FUNCTION public.get_activity_feed_page(uuid, integer, timestamptz, bigint)
TO authenticated;

CREATE OR REPLACE FUNCTION public.mark_activity_feed_seen(
  p_user_id uuid,
  p_activity_ids bigint[] DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_updated_count integer;
BEGIN
  IF p_activity_ids IS NULL OR cardinality(p_activity_ids) = 0 THEN
    UPDATE public.activity_feed af
    SET seen = true
    WHERE af.user_id = p_user_id
      AND af.seen = false;
  ELSE
    UPDATE public.activity_feed af
    SET seen = true
    WHERE af.user_id = p_user_id
      AND af.seen = false
      AND af.id = ANY(p_activity_ids);
  END IF;

  GET DIAGNOSTICS v_updated_count = ROW_COUNT;
  RETURN v_updated_count;
END;
$$;

GRANT EXECUTE ON FUNCTION public.mark_activity_feed_seen(uuid, bigint[])
TO authenticated;

CREATE OR REPLACE FUNCTION public.insert_activity_for_expense_event(
  p_event_type text,
  p_expense_row jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_expense_id uuid := NULLIF(p_expense_row ->> 'id', '')::uuid;
  v_group_id uuid := NULLIF(p_expense_row ->> 'group_id', '')::uuid;
  v_created_by uuid := NULLIF(p_expense_row ->> 'created_by', '')::uuid;
  v_paid_by uuid := NULLIF(p_expense_row ->> 'paid_by', '')::uuid;
  v_metadata jsonb;
  v_inserted_count integer := 0;
BEGIN
  IF v_expense_id IS NULL THEN
    RETURN;
  END IF;

  v_metadata := jsonb_build_object(
    'expense_id', v_expense_id,
    'group_id', v_group_id,
    'created_by', v_created_by,
    'paid_by', v_paid_by,
    'amount', p_expense_row -> 'amount',
    'currency', p_expense_row -> 'currency',
    'description', p_expense_row -> 'description',
    'category', p_expense_row -> 'category'
  );

  IF to_regclass('public.expense_splits') IS NOT NULL THEN
    EXECUTE
      'INSERT INTO public.activity_feed (user_id, type, metadata)
       SELECT DISTINCT es.user_id, $1, $2
       FROM public.expense_splits es
       WHERE es.expense_id = $3
         AND es.user_id IS NOT NULL'
    USING p_event_type, v_metadata, v_expense_id;

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
  END IF;

  IF v_inserted_count = 0
    AND v_group_id IS NOT NULL
    AND to_regclass('public.group_members') IS NOT NULL THEN
    EXECUTE
      'INSERT INTO public.activity_feed (user_id, type, metadata)
       SELECT DISTINCT gm.user_id, $1, $2
       FROM public.group_members gm
       WHERE gm.group_id = $3
         AND gm.user_id IS NOT NULL'
    USING p_event_type, v_metadata, v_group_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.activity_feed_on_expense_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.insert_activity_for_expense_event('expense_created', to_jsonb(NEW));
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.activity_feed_on_expense_delete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.insert_activity_for_expense_event('expense_deleted', to_jsonb(OLD));
  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.activity_feed_on_settlement_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_settlement_row jsonb := to_jsonb(NEW);
  v_from_user uuid := NULLIF(v_settlement_row ->> 'from_user', '')::uuid;
  v_to_user uuid := NULLIF(v_settlement_row ->> 'to_user', '')::uuid;
  v_metadata jsonb;
BEGIN
  v_metadata := jsonb_build_object(
    'settlement_id', v_settlement_row -> 'id',
    'group_id', v_settlement_row -> 'group_id',
    'from_user', v_settlement_row -> 'from_user',
    'to_user', v_settlement_row -> 'to_user',
    'amount', v_settlement_row -> 'amount',
    'currency', v_settlement_row -> 'currency',
    'status', v_settlement_row -> 'status'
  );

  INSERT INTO public.activity_feed (user_id, type, metadata)
  SELECT DISTINCT participant.user_id, 'settlement_created', v_metadata
  FROM (
    VALUES (v_from_user), (v_to_user)
  ) AS participant(user_id)
  WHERE participant.user_id IS NOT NULL;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.expenses') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_activity_feed_expense_insert ON public.expenses';
    EXECUTE
      'CREATE TRIGGER trg_activity_feed_expense_insert
       AFTER INSERT ON public.expenses
       FOR EACH ROW
       EXECUTE FUNCTION public.activity_feed_on_expense_insert()';

    EXECUTE 'DROP TRIGGER IF EXISTS trg_activity_feed_expense_delete ON public.expenses';
    EXECUTE
      'CREATE TRIGGER trg_activity_feed_expense_delete
       BEFORE DELETE ON public.expenses
       FOR EACH ROW
       EXECUTE FUNCTION public.activity_feed_on_expense_delete()';
  END IF;

  IF to_regclass('public.settlements') IS NOT NULL THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_activity_feed_settlement_insert ON public.settlements';
    EXECUTE
      'CREATE TRIGGER trg_activity_feed_settlement_insert
       AFTER INSERT ON public.settlements
       FOR EACH ROW
       EXECUTE FUNCTION public.activity_feed_on_settlement_insert()';
  END IF;
END;
$$;
